encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("new", views.new, name="new"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random", views.random, name="random")
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("urls"))
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from random import randint

from django.http import HttpRequest, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry(request, title):
    content = util.get_entry(title)
    if content == None:
        return HttpResponseBadRequest("Bad Request: the requested page was not found")

    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": content
    })


def search(request):
    if request.method == "POST":
        title = request.POST["q"]
        entries = util.list_entries()
        contents = []

        for entry in entries:
            entry = entry
            if entry.find(title) != -1:
                contents.append(entry)

        if len(contents) == 0:
            return HttpResponseBadRequest("Bad Request: the requested page was not found")

        return render(request, "encyclopedia/search.html", {
            "contents": contents
        })

    return HttpResponseRedirect(reverse("wiki:index"))


def new(request):
    if request.method == "POST":
        title = request.POST["title"]
        content = request.POST["content"]
        entries = util.list_entries()

        for entry in entries:
            if entry == title:
                return HttpResponseBadRequest("Bad Request: the encyclopedia entry title already exists")

        util.save_entry(title, content)

        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "content": content
        })

    return render(request, "encyclopedia/new.html")


def edit(request, title):
    content = util.get_entry(title)
    if content == None:
        return HttpResponseBadRequest("Bad Request: the requested page was not found")

    if request.method == "POST":
        new = request.POST["new"]
        util.save_entry(title, new)
        return HttpResponseRedirect(reverse("wiki:entry", args=(title,)))

    return render(request, "encyclopedia/edit.html", {
        "title": title,
        "content": content
    })


def random(request):
    entries = util.list_entries()
    random_num = randint(0, len(entries) - 1)
    title = entries[random_num]
    content = util.get_entry(title)

    if content == None:
        return HttpResponseBadRequest("Bad Request: the requested page was not found")

    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": content
    })

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<form action="{% url 'wiki:edit' title %}" method="POST">
    {% csrf_token %}
    <textarea name="new" cols="30" rows="10">
        {{ content }}
    </textarea>
    <input type="submit" value="Save">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
{{ content }}
<br>
<a href="{% url 'wiki:edit' title %}">Edit</a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>All Pages</h1>

<ul>
    {% for entry in entries %}
    <li><a href="{% url 'wiki:entry' entry %}">{{ entry }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form action="{% url 'wiki:search' %}" method="POST">
                {% csrf_token %}
                <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
            </form>
            <div>
                <a href="{% url 'wiki:index' %}">
                    Home
                </a>
            </div>
            <div>
                <a href="{% url 'wiki:new' %}">
                    Create New Page
                </a>
            </div>
            <div>
                <a href="{% url 'wiki:random' %}">
                    Random Page
                </a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</body>

</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
New Page
{% endblock %}

{% block body %}
<form action="{% url 'wiki:new' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="title" placeholder="Title" autofocus>
    <textarea name="content" cols="30" rows="10" placeholder=" Enter your content here..."></textarea>
    <input type="submit" value="Save">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Search
{% endblock %}

{% block body %}
<ul>
    {% for content in contents %}
    <li><a href="{% url 'wiki:entry' content %}">{{ content }}</a></li>
    {% endfor %}
</ul>
{% endblock %}